= C++ example project scanned on SonarCloud using Azure Pipelines
// URIs:
:uri-qg-status: https://sonarcloud.io/dashboard?id=sonarsource-cfamily-examples_macos-xcode-azure-sc
:img-qg-status: https://sonarcloud.io/api/project_badges/measure?project=sonarsource-cfamily-examples_macos-xcode-azure-sc&metric=alert_status
:uri-build-status: https://dev.azure.com/sonarsource-cfamily-examples/macos-xcode-azure-sc/_build/latest?definitionId=2
:img-build-status: https://dev.azure.com/sonarsource-cfamily-examples/macos-xcode-azure-sc/_apis/build/status/sonarsource-cfamily-examples.macos-xcode-azure-sc

image:{img-build-status}[Build Status, link={uri-build-status}]
image:{img-qg-status}[Quality Gate Status,link={uri-qg-status}]

*This project is analysed on https://sonarcloud.io/dashboard?id=sonarsource-cfamily-examples_macos-xcode-azure-sc[SonarCloud]!*


It is very easy to analyze a C, C++ and Objective-C project with SonarCloud https://docs.sonarcloud.io/getting-started/azure-devops/[on Azure DevOps]:

. Create a `sonar-project.properties` file to store your configuration
. Install SonarCloud extension for your organization:
.. Open Organization settings (in the bottom left corner of organization view)
.. Open "Extensions" page (in the General category)
.. Press "Browse marketplace" and find "SonarCloud"
.. Select your organization and click "Install"
. Add the SonarCloud connection to your project:
.. Open Project settings (in the bottom left corner of project page)
.. Open "Service connections" page (in the Pipelines category)
.. Press "New connection" and select the "SonarCloud"
.. Fill in the `SONAR_TOKEN`
.. Name your connection `SonarCloud` (to reference it later in `azure-pipelines.yml`)
. In your `azure-pipelines.yml` file:
.. Add the `SonarCloudPrepare` task and configure it:
* Specify the `SonarCloud Service Endpoint` as `SonarCloud` - the connection you created earlier
* Choose your `organization`
* Choose "Use standalone scanner" (`scannerMode: 'CLI'`)
* Choose "Store configuration with my source code (sonar-project.properties)" (`configMode: 'file'`)
.. Add a task to download the https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/#analysis-steps-using-build-wrapper[Build Wrapper]
.. Wrap your compilation with the Build Wrapper
.. Add the `SonarCloudAnalyze` task

You can take a look at the link:sonar-project.properties[sonar-project.properties] and link:azure-pipelines.yml[azure-pipelines.yml] to see it in practice.

= Documentation

- https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/[Documentation overview of the C, C++ and Objective-C analyzer]
- https://docs.sonarcloud.io/getting-started/azure-devops/[Documentation of using SonarCloud with Azure DevOps]
- https://docs.sonarcloud.io/advanced-setup/languages/c-family/prerequisites/#generating-a-compilation-database[Generating a compilation database (compile_commands.json)]
- https://docs.sonarsource.com/sonarcloud/advanced-setup/languages/c-family/running-the-analysis/[Running the analysis in Compilation Database mode]

== Warnings

The following warning may appear during invocation of `/build-wrapper-macosx-x86`. To best of our knowledge does not affect the result of the analysis:
----
dyld: warning: could not load inserted library '/Users/runner/.sonar/build-wrapper-macosx-x86/libinterceptor.dylib' into hardened process because no suitable image found.  Did find:
	/Users/runner/.sonar/build-wrapper-macosx-x86/libinterceptor.dylib: code signature in (/Users/runner/.sonar/build-wrapper-macosx-x86/libinterceptor.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
----
For details please refer to following https://jira.sonarsource.com/browse/CPP-1640[ticket] and https://community.sonarsource.com/t/dyld-warning-could-not-load-inserted-library-applications-sonar-scanner-bin-libinterceptor-dylib-into-hardened-process-because-no-suitable-image-found/1806[community thread].


= macOS\XCodeBuild

A build of the https://github.com/sonarsource-cfamily-examples/code[code repository] on a macOS using XCode build system.

To build the code run from the repository root directory:
----
xcodebuild
----

= Code Description

An example of a flawed C++ code. The https://github.com/sonarsource-cfamily-examples/code[code repository] can be https://github.com/sonarsource-cfamily-examples/automatic-analysis-sc[analyzed automatically], but it can also be compiled with different build systems using different CI pipelines on Linux, macOS, and Windows.

The https://github.com/sonarsource-cfamily-examples/code[code repository] is forked into other repositories in https://github.com/sonarsource-cfamily-examples[this collection] to add a specific build system, platform, and CI.
The downstream repositories are analyzed either with https://www.sonarqube.org/[SonarQube] or https://sonarcloud.io/[SonarCloud].

You can find examples for:

* https://github.com/sonarsource-cfamily-examples?q=linux[Linux]
* https://github.com/sonarsource-cfamily-examples?q=macos[macOS]
* https://github.com/sonarsource-cfamily-examples?q=windows[Windows]

Using the following build systems:

* https://github.com/sonarsource-cfamily-examples?q=cmake[CMake]
* https://github.com/sonarsource-cfamily-examples?q=autotools[GNU Autotools]
* https://github.com/sonarsource-cfamily-examples?q=xcode[Xcode]
* https://github.com/sonarsource-cfamily-examples?q=msbuild[MSBuild]

Running on the following CI services:

* https://github.com/sonarsource-cfamily-examples?q=azure[Azure DevOps]
* https://github.com/sonarsource-cfamily-examples?q=gh-actions[GitHub Actions]
* https://github.com/sonarsource-cfamily-examples?q=travis[Travis]
* https://github.com/sonarsource-cfamily-examples?q=jenkins[Jenkins]
* https://github.com/sonarsource-cfamily-examples?q=gitlab[GitLab CI]
* https://github.com/sonarsource-cfamily-examples?q=bitbucket[BitBucket Pipelines]
* Additionally, https://github.com/orgs/sonarsource-cfamily-examples/repositories?q=otherci[generic examples] demonstrate integration with other CIs and https://github.com/orgs/sonarsource-cfamily-examples/repositories?q=manual[manual-configuration examples] should help you if you are running locally.

Configured for analysis on:

* https://github.com/sonarsource-cfamily-examples?q=-sq[SonarQube]
* https://github.com/sonarsource-cfamily-examples?q=-sc[SonarCloud]

You can find also a few examples demonstrating:

* https://github.com/orgs/sonarsource-cfamily-examples/repositories?q=compdb[The use of Compilation Database (compile_commands.json)]
* https://github.com/orgs/sonarsource-cfamily-examples/repositories?q=topic%3Acoverage[Test coverage]


See link:./examples-structure.adoc[examples-structure.adoc] for a description of the structure of https://github.com/sonarsource-cfamily-examples[this GitHub organization] and the relations between its different repositories.
